name: savora
description: "A blogger application."
publish_to: 'none'

version: 2.1.2+20251102

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  image_picker: ^1.2.0
  supabase_flutter: ^2.10.3
  flutter_local_notifications: ^17.2.1
  intl: ^0.20.2
  google_sign_in: ^6.3.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/icon/logo.png
    - assets/images/googlelogo.png