name: savora
description: "A blogger application."
publish_to: 'none'

version: 2.3.0+20251111

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  image_picker: ^1.2.0
  http: ^1.1.0
  share_plus: ^12.0.1
  path_provider: ^2.1.3
  video_player: ^2.8.0
  chewie: ^1.7.0
  supabase_flutter: ^2.10.3
  flutter_local_notifications: ^19.5.0
  intl: ^0.20.2
  google_sign_in: ^7.2.0
  flutter_launcher_icons: ^0.14.4
  logger: ^2.6.2
  app_links: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/icon/logo.png
    - assets/images/googlelogo.png